name: Copy File Workflow

on:
  push:
    branches: [ "main" ]
    
jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy File
        run: |
          # file and source/destination directories
          source_file="Folder1/file1.txt"
          destination_folder="folder2/"

          # Copy the file to the destination folder
          cp "${source_file}" "${destination_folder}"

      - name: Commit Changes
        run: |
          git config --local user.email "gdzhorobek@github.com"
          git config --local user.name "guldzh"
          git add .
          git commit -m "Copy file using GitHub Actions"
          git push
